#!/usr/bin/env bash
# change nginx config file and restart nginx server
sed -i 's/\tlisten 8080 default_server;/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/^\tlisten \[::\]:8080 default_server ipv6only=on;/\tlisten \[::\]:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
/etc/init.d/nginx restart
