#!/usr/bin/env bash
# FizzBuzz
i=1
while [ $i -le 100 ]
do
    [ "$((i % 3))" = 0 ]  && echo -n 'Fizz'
    [ "$((i % 5))" = 0 ] && echo -n 'Buzz'
    [ "$((i % 3))" != 0 ] && [ "$((i % 5))" != 0 ] && echo -n $i
    echo && let "i += 1"
done
