#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times.
# print back luck for 4, good luck for 8
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	echo bad luck
    elif [ $i -eq 8 ]
    then
	echo good luck
    else
	echo Holberton School
    fi
    let "i += 1"
done
