#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
# display bad luck from China for 4th
# display bad luck from Japan for 9th
# display bad luck from Italy for 17
i=1
while [ $i -le 20 ]
do
    echo $i
    if [ $i -eq 4 ]
    then
	echo bad luck from China
    elif [ $i -eq 9 ]
    then
	echo bad luck from Japan
    elif [ $i -eq 17 ]
    then
	echo bad luck from Italy
    fi
    let "i += 1"
done
