#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
# display bad luck from China for 4th
# display bad luck from Japan for 9th
# display bad luck from Italy for 17
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case "$i" in
    4) 	echo bad luck from China
	;;
    9)  echo bad luck from Japan
	;;
    17)	echo bad luck from Italy
	;;
    esac
    let "i += 1"
done
