#!/usr/bin/env bash
cp /etc/hosts ~/temp
sed -i '/[\d.]*[ \t]localhost/c\127.0.0.2 localhost' ~/temp
s="$(sed -n '/.*facebook[.]com.*/p' ~/temp)"
if [ "a$s" = "a" ]
then
    sed -i '2i8.8.8.8 facebook.com' ~/temp
else
    sed -i '/[\d.]*[ \t]*facebook[.]com/c\8.8.8.8 facebook.com' ~/temp
fi
mv -f ~/temp /etc/hosts
