#!/usr/bin/env bash
# change localhost ip to 127.0.0.2
# change facebook ip tp 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i '/[\d.]*[ \t]localhost/c\127.0.0.2 localhost' ~/hosts.new
s="$(sed -n '/.*facebook[.]com.*/p' ~/hosts.new)"
if [ "a$s" = "a" ]
then
    sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
else
    sed -i '/[\d.]*[ \t]*facebook[.]com/c\8.8.8.8 facebook.com' ~/hosts.new
fi
mv -f ~/hosts.new /etc/hosts
